apiVersion: v1
kind: Pod
metadata:
  name: node-pod-af
spec:
  containers:
  - name: node-nginx-af
    image: nginx
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                - worker
