apiVersion: v1
kind: Pod
metadata:
  name: pod-config-single
  labels:
      name: pod-config-single

spec:
  containers:
    - name: nginx-container-single
      image: nginx
      ports:
        - containerPort: 8080
      env:
        - name: DEBUG
          valueFrom:
              configMapKeyRef:
                  name: app-config
                  key: DEBUG
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
      volumeMounts:
        - name: app-secret-volume
          readOnly: true
          mountPath: "/opt/app-secret-volume"
  volumes:
    - name: app-secret-volume
      secret:
          secretName: app-secret

