apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 1Gi
    defaultRequest: # this section defines default requests
      cpu: 500m
      memoery: 1Gi
    max: # max and min define the limit range
      cpu: "1"
      memoery: 1Gi
    min:
      cpu: 100m
      memoery: 500Mi
    type: Container
